### ISSUE TITLE
Cannot find module 'event-stream'...

### ISSUE THREAD

**Issue by oddpxl** [timburgess/brackets-ftp-sync#58] opened 2015-04-14 18:19 UTC
Hi All,

Great plugin!!

Had a lot of love for it until this morning...
..when it started saying " Cannot find module 'event-stream' " instead of happily uploading... :(

I'm using Brackets Release 1.2 build 1.2.0-15697 (release 8f82e2a97) 
build timestamp: Sun Feb 22 2015 22:34:50 GMT-0800...on OSX 10.9.5 with Safari / Chrome / Firefox.

Tried re-installing the plugin twice, also went down one version...same problem...also re-installed Brackets...no luck.

Haven't really changed anything on my system so no idea why it stopped working.

Any ideas??

//O.

**Comment by Christian1984** [comment] 2015-04-14 18:40
Same here! I am also on 1.2.

**Comment by Kevincredible** [comment] 2015-04-14 21:23
I'm having the same exact issue. v1.2

**Comment by timburgess** [comment] 2015-04-14 23:50
Thanks for the feedback. I'm looking into this to see if I can reproduce it.

**Comment by christraverse** [comment] 2015-04-15 11:04
Having the same issue here since v1.2

**Comment by Jkleinjunge** [comment] 2015-04-16 10:43
the same issue for me

**Comment by smoyzasoboy** [comment] 2015-04-16 12:41
have same issue right now

**Comment by victorlap** [comment] 2015-04-16 18:20
I have the same issue here
Brackets version sprint 2 build 1.2.0-15697 (release 8f82e2a97)

**Comment by PandawanFr** [comment] 2015-04-17 01:17
Same issue
I'm on V1.2, MacOSX Yosemite if it helps

**Comment by alexmasters** [comment] 2015-04-22 07:38
Same here, still an issue. Any news on whether this will be fixed soon? Or which versions to use instead?

Thanks.

**Comment by IntellectProductions** [comment] 2015-04-24 12:58
Same issue...

**Comment by SteFilms** [comment] 2015-04-25 13:35
Same here...

**Comment by leesaenz** [comment] 2015-04-29 00:12
Same issue.  Mac OS X 10.10 Yosemite.

**Comment by PandawanFr** [comment] 2015-04-29 00:13
Yeah, I am on OSX Yosemite too

**Comment by rolandlawrence** [comment] 2015-04-30 19:34
yip having the same error. Looks like its a great plugin for brackets 1.3. Alas no joy.

**Comment by LouLeGrain** [comment] 2015-05-02 00:34
Same on brackets 1.3.0-16022 (release cd0a6aae5) on ubuntu 14.04

**Comment by Emsanator** [comment] 2015-05-02 11:36
Same Issue (brackets 1.3 - windows 8.1)

**Comment by AndersMoberg** [comment] 2015-05-03 12:38
I've also got this error.
Brackets (windows): **sprint 3 build 1.3.0-16022 (release cd0a6aae5)**
FTP-Sync: *2.0.3*

**Comment by TamjidMd** [comment] 2015-05-04 03:15
I having same error msg. :(
Brackets version 1.3 in Linux Mint

**Comment by deavy** [comment] 2015-05-06 08:29
Same issue 

sprint 3 build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Fri Apr 24 2015 14:11:10 GMT+0100

**Comment by QuaintShanty** [comment] 2015-05-07 10:16
Same issue. v2.03 - Windows 8.1

**Comment by towerrounder** [comment] 2015-05-07 11:36
Same issue here

**Comment by ansonwolfe** [comment] 2015-05-16 01:38
Same issue. 
 
Release 1.3 build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Mon May 11 2015 02:49:32 GMT-0700

**Comment by arberpolis** [comment] 2015-05-17 12:58
same issue for me as well. Brackets Release 1.3 build 1.3.0-16022 (release cd0a6aae5)

**Comment by pisandelli** [comment] 2015-05-24 14:40
Any fix?
Brackets 1.3
Ubuntu 15.04

**Comment by joelamos** [comment] 2015-05-28 02:49
Same here.

Brackets: Release 1.3 build 1.3.0-16022 (release cd0a6aae5)
FTP-Sync Plus: v 2.0.3

**Comment by timburgess** [comment] 2015-05-28 22:13
I have updated the node module dependencies and this has fixed the event-stream issue I believe. There is a new 2.0.4 build zip file in the project root. Please try this and confirm that FTP works - I haven't seen the event-stream issue with this build. I would also be keen to get feedback on SFTP functionality as I have only done limited testing to date with SFTP.

**Comment by pisandelli** [comment] 2015-05-28 23:05
2.0.4 Build is now working on Brackets 1.3.0-16022 (release cd0a6aae5) (Tested Just FTP)
Ubuntu 15.04 64bit

Thanks!

**Comment by timburgess** [comment] 2015-05-28 23:38
:+1:

**Comment by joelamos** [comment] 2015-05-29 01:16
FTP working for me as well!

**Comment by timburgess** [comment] 2015-05-29 07:20
:+1: Please advise what OS and Brackets version you're using as well.

**Comment by incredibleweirdo** [comment] 2015-05-31 18:20
2.0.4 Build working on Brackets 1.3.0-16022, Mac OS X 10.7.5.

**Closed** 2015-05-31 21:00 UTC

**Comment by kevinberonilla** [comment] 2015-06-01 13:02
OS X Yosemite with Brackets 1.3.0-16022 is now working correctly with the latest build you posted. Thanks for the fix!

**Comment by stevebaxter** [comment] 2015-06-08 13:12
All working for me again - OS X 10.10 Brackets 1.3 build 1.3.0-16022. Thanks!!

**Comment by ryanmcfall** [comment] 2015-07-13 19:31
I had this issue, and the 2.0.4 build fixed it.

Now I am trying to hack on the ftp-sync source code, and have this issue when using the version I've pulled from github.  Here is what I have done
*  forked the repo
*  Used git clone to get a local copy of my forked version
*  Make a minor change to the HTML for the dialog box so I could be sure I'm running my version
*  Copy the contents of the src folder into a new folder in the extensions folder
*  Restart Brackets
*  Click the icon to perform the sync, verify that my change has been made
*  Click the Upload button to commence the FTP process

I have also tried:
*  npm install from within the root of the cloned repo
*  grunt
*  Drag the generated zip file into the Extension manager

In both cases, I get the unable to load event-stream module error.

FWIW:
*  Brackets Release 1.3 build 1.3.0-16022
*  Mac OS X Yosemite, version 10.10.3

Any ideas?

**Comment by timburgess** [comment] 2015-07-14 04:26
In <code>src/node/node_modules</code>, there is a <code>jsftp</code> directory. jsftp is one of the dependencies that ftp-sync has. You will need to cd to the jsftp directory and in there, run <code>npm install</code> to install the modules that jsftp itself it dependent upon.

Thanks for trying the code out!

**Comment by ryanmcfall** [comment] 2015-07-14 12:02
@timburgess - Thanks, running `npm install` in the `jsftp` directory did the trick.

Just so you know, I am playing around with caching the last upload date of files, so that when the synchronization occurs, only a local date check needs to be done for files that haven't been modified since the last sync.  For large projects, I suspect this will significantly speed up the time that it takes to sync.

**Comment by timburgess** [comment] 2015-07-16 22:32
Good one. At the time of adding <code>jsftp</code>, I hesitated adding it's dependencies to the repo as there are a huge number. I'm thinking now that I may as well add them anyway - it's not like they will change and it won't make the end <code>.zip</code> file any bigger.
